### ISSUE TITLE
Geforce now steaming service

### ISSUE THREAD

**Issue by thelege2nd** [Lynnette177/Rigel-Overwatch-External#12]
hello, is this fully external? does it depend on anything internally? I play on Geforce now game streaming service. The game isn't basically running on my own Pc but is in the cloud. will the bot work with it?

**Comment by Lynnette177** [comment]
It's fully external, and for your question,No.

**Comment by thelege2nd** [comment]
Thanks. Why wouldn't it work if its fully external? I haven't tried it yet.

**Comment by Lynnette177** [comment]
You even didn't understand what "external" means.&nbsp;&nbsp;


Mercy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lord ***@***.***&gt;; 
发送时间: 2024年9月26日(星期四) 晚上6:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lynnette177/Rigel-Overwatch-External] Geforce now steaming service (Issue #12)















Thanks. Why wouldn't it work if its fully external? I haven't tried it yet.

**Comment by thelege2nd** [comment]
I didn't, that's why I'm asking you. Would you be kind and tell me? I appreciate your knowledge 🙏

**Comment by Lynnette177** [comment]
Internal means inject code into the program, while external don't inject but still need to operate target process's memory. Both of them need the game to run on your local computer instead of streaming. The game even didn't run on your computer how can the cheat access its memory?&nbsp;


Mercy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lord ***@***.***&gt;; 
发送时间: 2024年9月26日(星期四) 晚上7:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lynnette177/Rigel-Overwatch-External] Geforce now steaming service (Issue #12)















I didn't, that's why I'm asking you. Would you be kind and tell me? I appreciate your knowledge 🙏

**Comment by thelege2nd** [comment]
I understand now. That's why I asked if it's "fully" external, meaning it doesn't require a specific target process but only screen reading, similar to pixel color bots. But now I understand, thank you for the clarification. What exactly does it read from the game process? Is it only sending mouse events there, or is there something else? I'm asking because I think I could modify it to read the screen directly from Geforce Now, assuming this aimbot targets colors.

**Comment by Lynnette177** [comment]
That’s impossible.





------------------ Original ------------------
From: Lord Sam ***@***.***&gt;
Date: Thu,Sep 26,2024 7:58 PM
To: Lynnette177/Rigel-Overwatch-External ***@***.***&gt;
Cc: Lynnette ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Lynnette177/Rigel-Overwatch-External] Geforce now steamingservice (Issue #12)





 
I understand now. That's why I asked if it's "fully" external, meaning it doesn't require a specific target process but only screen reading, similar to pixel color bots. But now I understand, thank you for the clarification. What exactly does it read from the game process? Is it only sending mouse events there, or is there something else? I'm asking because I think I could modify it to read the screen directly from Geforce Now, assuming this aimbot targets colors.
